module.exports = ({
    SET_LOADER_FOR_LOGIN: 'SET_LOADER_FOR_LOGIN',
    SET_LOGIN_ERROR_MESSAGE: 'SET_LOGIN_ERROR_MESSAGE',
    USERNAME_PASSWORD_STORE: 'USERNAME_PASSWORD_STORE',
    SET_LOGIN_USERNAME: 'SET_LOGIN_USERNAME',
    SET_LOGIN_PASSWORD: 'SET_LOGIN_PASSWORD',
    RESET_STATE_FOR_LOGIN: 'RESET_STATE_FOR_LOGIN',
    LOGGED_IN_ROUTE: 'LOGGED_IN_ROUTE',
    API_URL: 'https://pokeapi.co/api/v2/'
})